name: Dependency Updates

on:
  schedule:
    # Runs weekly on Monday at 02:00 UTC
    - cron: "0 2 * * 1"
  workflow_dispatch: # allows manual triggering
  pull_request:
  push:
    branches:
      - main

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository with token
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Step 3: Install current dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Check for outdated dependencies
      - name: Check outdated dependencies
        run: npm outdated || true

      # Step 5: Update dependencies
      - name: Update dependencies
        run: npm update

      # Step 6: Run tests to verify updates
      - name: Run tests
        run: npm test

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Automated dependency update
          branch: dependency-updates
          title: Automated dependency update
          body: This PR updates project dependencies.

