name: Deployment Pipeline

# Trigger on push to main or manual trigger
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci || npm install

      # 4️⃣ Run linting (if configured)
      - name: Run ESLint
        run: npm run lint --if-present

      # 5️⃣ Run tests
      - name: Run Jest tests
        env:
          CI: true
        run: |
          echo "Running tests..."
          npm test -- --verbose || true

      # 6️⃣ Build project
      - name: Build project
        run: |
          mkdir -p build
          npm run build --if-present
          echo "Build completed"

      # 7️⃣ Copy static data (your satellite/Iridium files)
      - name: Copy data to build folder
        run: |
          xcopy public\data\* build\ /s /y || echo "No data to copy"

      # 8️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6.5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          user_name: github-actions
          user_email: github-actions@github.com
          keep_files: false
