name: Build and Deploy Docusaurus Documentation

on:
  push:
    branches: [ main ]  # change if your default branch is different
    paths:
      - 'my-docs/docs/**'                # trigger only when docs change
      - 'my-docs/docusaurus.config.js'   # rebuild if config changes
      - 'my-docs/package.json'           # rebuild if dependencies change
      - '.github/workflows/documentation.yml' # rerun if workflow changes

  workflow_dispatch:  # 👈 allows manual trigger from GitHub Actions tab

permissions:
  contents: write  # required to deploy to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full git history for Docusaurus versioning if used later

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd my-docs
          # Try npm ci if lockfile exists, else fallback to npm install
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build Docusaurus site
        run: |
          cd my-docs
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./my-docs/build
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
