name: Scheduled Tests

on:
  schedule:
    # Runs daily at 11:00 AM UTC
    - cron: "0 11 * * *"
  workflow_dispatch: # allows manual triggering

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (adjust version if needed)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run tests
        run: npm test

      # Step 5: Show logs
      - name: Show logs
        run: echo "Tests executed at 11:00 UTC"
